### ISSUE TITLE
Events are not posted to channel

### ISSUE THREAD

**Issue by andreas-bulling** [koyan/rocketchat-google-calendar#1]
Hi,

I set up the integration with Rocket.Chat 0.62.2 (can't use any higher version as long as the node problem is not fixed).

Everything went fine, including OAuth authentication. That is, I set up the integration as described in Rocket.Chat, I can run the python script, it finishes without error, and creates a file `sentEvents` with some cryptic content. However, the event is not posted to the corresponding channel.

Any suggestion for how to debug this?

**Comment by koyan** [comment]
Hi Andreas,
To debug it I would do the following:
a) Create a python file with just the following in it:

```
import requests
url = 'YOUR_CHANNEL_INCOMING_WEBHOOK_URL_HERE'
r = requests.post(url, 'TEST')
```
b) In RocketChat, in the script that processes your webhook, inside the `process_incoming_request({request}) {`  I would add the following two lines: 
```
   	console.log('Andreas Debugging starts here);
    	console.log(request.content);
   	console.log('Andreas Debugging ends here);
```
c) Then I would run the python script, and see if it produces anything in the rocketchat logs. 
If it does, then the problem is somewhere in the python script I have written and I would have to debug it step by step
If it does not, then your server does not send the request at all . Or maybe the url is wrong. Or maybe RocketChat cannot receive from the server you are sending (a firewall blocks requests). 

I hope this helps.
Konstantinos

**Comment by andreas-bulling** [comment]
Hi @koyan 
thanks a lot for your quick reply.

I did what you suggested and see the debug output on the console/logs.

**Comment by koyan** [comment]
Ok, in that case, your server is sending the messages. 
To further debug it, delete the sentEvents file (it contains a log of what it has already sent, so that it does not sent it again), create a few events in <30 mins in the future, and run the script. If you see it creating the "sentEvents" file (and it has data inside), then check your RocketChat logs to see if it received the data. If it received them, then the problem is with the script that processes it in the RocketChat side.

**Comment by andreas-bulling** [comment]
Did as you suggested. The file gets created and has three entries (for the three events I created before. But no message in the logs (took out the debug message before)

EDIT: Wait, now it works?!? Not sure what I did but now I can see the events in the corresponding channel...

**Comment by andreas-bulling** [comment]
I think we can close this - seems to work fine now. Sorry for the "wrong" issue...

**Comment by koyan** [comment]
Very glad it works.
